name: WebAssembly

exclude: [
  README.md,
  LICENSE,
  google66d80fe1bc71482a.html,
  Gemfile,
  Gemfile.lock,
  CNAME,
  design/LICENSE,
  design/Contributing.md,
  design/README.md,
  design/tools
]

destination: docs

permalink: pretty

defaults:
  -
    scope:
      path: "design"
    values:
      layout: "doc"
      type: "doc"
  -
    scope:
      path: "design/CodeOfConduct.md"
    values:
      layout: "community"
      type: "community"
      permalink: "/community/code-of-conduct/"
  -
    scope:
      path: "design/Events.md"
    values:
      layout: "community"
      type: "community"
      permalink: "/community/events/"